/**
 * Curated, static venue examples for heuristic journal suggestions.
 *
 * NOT scraped from Scimago / Clarivate / Elsevier rank DBs.
 * Names are well-known open or society-pattern venues used only as *examples*
 * for topical fit — never as acceptance or Q1/Q2 guarantees.
 */

export type VenueField =
  | 'cs'
  | 'ee'
  | 'biomed'
  | 'physics'
  | 'general'
  | 'ml'
  | 'systems'
  | 'communications'
  | 'semiconductors'
  | 'sensors'
  | 'materials'
  | 'devices';

/** How “complete” a venue usually expects the manuscript to be (heuristic only). */
export type VenueFormat =
  | 'full_article'
  | 'letter'
  | 'communication'
  | 'access_oa'
  | 'preprint'
  | 'survey';

export interface CuratedVenue {
  name: string;
  /** Short publisher / type hint for UI */
  publisherHint: string;
  fields: VenueField[];
  keywords: string[];
  /** Shown when matching this venue */
  caution?: string;
  /** Prefer when manuscript appears IEEE-citation oriented */
  ieeeOriented?: boolean;
  /** Prefer when paper looks like a survey / open-access short note */
  openAccess?: boolean;
  /** Soft format hint for gap-aware matching */
  format?: VenueFormat;
}

export const CURATED_VENUES: CuratedVenue[] = [
  // —— IEEE Access / letters / broad ——
  {
    name: 'IEEE Access',
    publisherHint: 'IEEE open-access multidisciplinary (example venue)',
    fields: ['cs', 'ee', 'ml', 'systems', 'communications', 'general', 'sensors', 'devices'],
    keywords: [
      'ieee',
      'algorithm',
      'neural',
      'deep learning',
      'wireless',
      'sensor',
      'embedded',
      'optimization',
      'signal',
      'image',
      'network',
      'iot',
      'robot',
      'semiconductor',
      'device',
    ],
    ieeeOriented: true,
    openAccess: true,
    format: 'access_oa',
    caution: 'Open-access APCs apply; topical fit ≠ acceptance.',
  },
  {
    name: 'IEEE Letters pattern (e.g. Electron Device Letters style)',
    publisherHint: 'IEEE short-letter style (name pattern only)',
    fields: ['ee', 'semiconductors', 'devices', 'materials'],
    keywords: ['transistor', 'mosfet', 'gan', 'sic', 'device', 'fabrication', 'threshold', 'mobility'],
    ieeeOriented: true,
    format: 'letter',
    caution: 'Letters expect tight novelty + short form — example pattern only.',
  },
  {
    name: 'IEEE Communications Letters (example pattern)',
    publisherHint: 'IEEE short communications pattern',
    fields: ['communications', 'ee'],
    keywords: ['wireless', 'mimo', 'ofdm', 'coding', 'channel', 'latency', 'throughput'],
    ieeeOriented: true,
    format: 'letter',
  },
  {
    name: 'IEEE Signal Processing Letters (example pattern)',
    publisherHint: 'IEEE short SP pattern',
    fields: ['ee', 'ml', 'communications'],
    keywords: ['signal processing', 'filter', 'estimation', 'spectrum', 'audio', 'speech', 'fft'],
    ieeeOriented: true,
    format: 'letter',
  },

  // —— IEEE transactions / journals (patterns) ——
  {
    name: 'IEEE Transactions on Neural Networks and Learning Systems (example pattern)',
    publisherHint: 'IEEE transactions-style venue (name pattern only)',
    fields: ['ml', 'cs'],
    keywords: [
      'neural network',
      'deep learning',
      'representation learning',
      'supervised',
      'classification',
      'cnn',
      'transformer',
      'reinforcement',
    ],
    ieeeOriented: true,
    format: 'full_article',
    caution: 'Example of an IEEE T-journal pattern — not a submission recommendation.',
  },
  {
    name: 'IEEE Transactions on Pattern Analysis and Machine Intelligence (example pattern)',
    publisherHint: 'IEEE transactions-style venue (name pattern only)',
    fields: ['ml', 'cs'],
    keywords: [
      'computer vision',
      'segmentation',
      'object detection',
      'image recognition',
      'pattern recognition',
      'feature',
      'pixel',
    ],
    ieeeOriented: true,
    format: 'full_article',
    caution: 'Example pattern only — verify scope on the society site.',
  },
  {
    name: 'IEEE Transactions on Wireless Communications (example pattern)',
    publisherHint: 'IEEE communications society pattern',
    fields: ['communications', 'ee'],
    keywords: [
      'wireless',
      'mimo',
      'ofdm',
      'beamforming',
      'channel',
      '5g',
      '6g',
      'spectrum',
      'antenna',
      'propagation',
    ],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Communications (example pattern)',
    publisherHint: 'IEEE ComSoc transactions pattern',
    fields: ['communications', 'ee'],
    keywords: ['modulation', 'coding', 'network coding', 'relay', 'interference', 'fading'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Journal on Selected Areas in Communications (example pattern)',
    publisherHint: 'IEEE JSAC-style special-issue pattern',
    fields: ['communications', 'systems', 'cs'],
    keywords: ['network', 'protocol', 'edge computing', 'sdn', '6g', 'satellite'],
    ieeeOriented: true,
    format: 'full_article',
    caution: 'Often special-issue driven — check open CFPs yourself.',
  },
  {
    name: 'IEEE Transactions on Electron Devices (example pattern)',
    publisherHint: 'IEEE EDS transactions pattern',
    fields: ['semiconductors', 'devices', 'ee', 'materials'],
    keywords: [
      'mosfet',
      'finfet',
      'transistor',
      'diode',
      'heterojunction',
      'carrier',
      'bandgap',
      'cmos',
    ],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Semiconductor Manufacturing (example pattern)',
    publisherHint: 'IEEE manufacturing / process pattern',
    fields: ['semiconductors', 'materials', 'ee'],
    keywords: ['fabrication', 'lithography', 'yield', 'wafer', 'etch', 'deposition', 'cmp'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Device and Materials Reliability (example pattern)',
    publisherHint: 'IEEE reliability pattern',
    fields: ['devices', 'semiconductors', 'materials'],
    keywords: ['reliability', 'aging', 'tddb', 'hot carrier', 'failure', 'burn-in', 'lifetime'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Sensors Journal (example pattern)',
    publisherHint: 'IEEE sensors council pattern',
    fields: ['sensors', 'ee', 'systems', 'devices'],
    keywords: [
      'sensor',
      'transducer',
      'mems',
      'biosensor',
      'gas sensor',
      'accelerometer',
      'calibration',
      'sensing',
    ],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Sensors Letters (example pattern)',
    publisherHint: 'IEEE short sensors pattern',
    fields: ['sensors', 'ee', 'devices'],
    keywords: ['sensor', 'mems', 'transducer', 'iot', 'wearable'],
    ieeeOriented: true,
    format: 'letter',
  },
  {
    name: 'IEEE Transactions on Instrumentation and Measurement (example pattern)',
    publisherHint: 'IEEE I&M pattern',
    fields: ['sensors', 'ee', 'systems'],
    keywords: ['measurement', 'metrology', 'calibration', 'instrumentation', 'adc', 'daq'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Microwave Theory and Techniques (example pattern)',
    publisherHint: 'IEEE MTT pattern',
    fields: ['ee', 'communications', 'devices'],
    keywords: ['microwave', 'rf', 'mmwave', 'antenna', 'waveguide', 'filter', 'amplifier'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Power Electronics (example pattern)',
    publisherHint: 'IEEE PELS pattern',
    fields: ['ee', 'devices'],
    keywords: ['converter', 'inverter', 'power electronics', 'switching', 'gan', 'sic', 'motor'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Industrial Electronics (example pattern)',
    publisherHint: 'IEEE IES pattern',
    fields: ['ee', 'systems', 'devices'],
    keywords: ['industrial', 'motor drive', 'plc', 'automation', 'control', 'fault diagnosis'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Control Systems Technology (example pattern)',
    publisherHint: 'IEEE CSS applications pattern',
    fields: ['systems', 'ee'],
    keywords: ['control', 'pid', 'state estimation', 'observer', 'stability', 'mpc'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Robotics (example pattern)',
    publisherHint: 'IEEE robotics pattern',
    fields: ['systems', 'cs', 'ml'],
    keywords: ['robot', 'manipulator', 'slam', 'navigation', 'grasping', 'humanoid'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Biomedical Engineering (example pattern)',
    publisherHint: 'IEEE EMB pattern',
    fields: ['biomed', 'ee', 'sensors'],
    keywords: ['biomedical', 'ecg', 'eeg', 'medical imaging', 'prosthetic', 'physiological'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Journal of Biomedical and Health Informatics (example pattern)',
    publisherHint: 'IEEE informatics / health pattern',
    fields: ['biomed', 'ml', 'cs'],
    keywords: ['health informatics', 'ehr', 'wearable', 'telemedicine', 'clinical decision'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Medical Imaging (example pattern)',
    publisherHint: 'IEEE medical imaging pattern',
    fields: ['biomed', 'ml', 'ee'],
    keywords: ['mri', 'ct', 'ultrasound', 'segmentation', 'reconstruction', 'radiology'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Information Forensics and Security (example pattern)',
    publisherHint: 'IEEE IFS pattern',
    fields: ['cs', 'ml', 'systems'],
    keywords: ['security', 'cryptography', 'malware', 'authentication', 'privacy', 'adversarial'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Knowledge and Data Engineering (example pattern)',
    publisherHint: 'IEEE TKDE pattern',
    fields: ['cs', 'ml'],
    keywords: ['database', 'data mining', 'knowledge graph', 'query', 'big data', 'etl'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Software Engineering (example pattern)',
    publisherHint: 'IEEE TSE pattern',
    fields: ['cs', 'systems'],
    keywords: ['software', 'testing', 'verification', 'requirements', 'devops', 'refactor'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Parallel and Distributed Systems (example pattern)',
    publisherHint: 'IEEE TPDS pattern',
    fields: ['cs', 'systems'],
    keywords: ['distributed', 'parallel', 'cluster', 'mpi', 'scheduler', 'cloud'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Internet of Things Journal (example pattern)',
    publisherHint: 'IEEE IoT pattern',
    fields: ['systems', 'communications', 'sensors', 'cs'],
    keywords: ['iot', 'edge', 'mqtt', 'smart city', 'lpwan', 'gateway'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Transactions on Circuits and Systems I/II (example pattern)',
    publisherHint: 'IEEE CAS pattern',
    fields: ['ee', 'devices'],
    keywords: ['circuit', 'analog', 'vlsi', 'oscillator', 'filter', 'amplifier', 'mixed-signal'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Journal of Solid-State Circuits (example pattern)',
    publisherHint: 'IEEE SSCS pattern',
    fields: ['ee', 'semiconductors', 'devices'],
    keywords: ['cmos', 'adc', 'pll', 'serdes', 'memory', 'chip', 'layout'],
    ieeeOriented: true,
    format: 'full_article',
  },
  {
    name: 'IEEE Photonics Journal / Technology Letters (example pattern)',
    publisherHint: 'IEEE photonics pattern',
    fields: ['physics', 'ee', 'devices', 'materials'],
    keywords: ['photonic', 'laser', 'optical', 'waveguide', 'fiber', 'lidar', 'plasmon'],
    ieeeOriented: true,
    format: 'communication',
  },
  {
    name: 'IEEE Nanotechnology / Nanotechnology Magazine pattern',
    publisherHint: 'IEEE nano pattern',
    fields: ['materials', 'devices', 'semiconductors', 'physics'],
    keywords: ['nano', 'nanowire', 'quantum dot', '2d material', 'graphene', 'mos2'],
    ieeeOriented: true,
    format: 'full_article',
  },

  // —— Materials / semiconductors / devices (broader OA examples) ——
  {
    name: 'MDPI Sensors (example title)',
    publisherHint: 'MDPI open-access sensors title (example only)',
    fields: ['sensors', 'ee', 'systems', 'devices'],
    keywords: ['sensor', 'iot', 'mems', 'biosensor', 'monitoring', 'calibration'],
    openAccess: true,
    format: 'access_oa',
    caution: 'MDPI venues vary widely; some campuses advise extra diligence — not an endorsement.',
  },
  {
    name: 'MDPI Electronics (example title)',
    publisherHint: 'MDPI open-access electronics title (example only)',
    fields: ['ee', 'devices', 'systems', 'semiconductors'],
    keywords: ['electronics', 'fpga', 'embedded', 'hardware', 'pcb', 'microcontroller'],
    openAccess: true,
    format: 'access_oa',
    caution: 'Example only — verify scope and institutional guidance.',
  },
  {
    name: 'MDPI Materials / Nanomaterials (example titles)',
    publisherHint: 'MDPI materials OA family (examples)',
    fields: ['materials', 'physics', 'semiconductors'],
    keywords: ['material', 'thin film', 'alloy', 'polymer', 'composite', 'nanomaterial'],
    openAccess: true,
    format: 'access_oa',
  },
  {
    name: 'MDPI Micromachines (example title)',
    publisherHint: 'MDPI MEMS / microdevices OA (example)',
    fields: ['devices', 'sensors', 'semiconductors'],
    keywords: ['mems', 'microfabrication', 'microfluidic', 'actuators'],
    openAccess: true,
    format: 'access_oa',
  },
  {
    name: 'AIP Applied Physics Letters (example pattern)',
    publisherHint: 'Short applied-physics letters pattern',
    fields: ['physics', 'materials', 'devices', 'semiconductors'],
    keywords: ['applied physics', 'thin film', 'heterostructure', 'optoelectronic'],
    format: 'letter',
    caution: 'Example pattern — confirm current scope yourself.',
  },
  {
    name: 'Journal of Applied Physics (example pattern)',
    publisherHint: 'Applied physics full-article pattern',
    fields: ['physics', 'materials', 'devices'],
    keywords: ['dielectric', 'magnetic', 'plasma', 'condensed matter', 'spectroscopy'],
    format: 'full_article',
  },
  {
    name: 'ACS Applied Materials & Interfaces (example pattern)',
    publisherHint: 'ACS applied materials pattern (verify OA options)',
    fields: ['materials', 'devices', 'sensors', 'semiconductors'],
    keywords: ['interface', 'coating', 'catalyst', 'electrode', 'perovskite', 'battery'],
    format: 'full_article',
    caution: 'Example topical fit only — not an ACS endorsement.',
  },
  {
    name: 'RSC Advances / Nanoscale Advances (OA example family)',
    publisherHint: 'Royal Society of Chemistry OA-style examples',
    fields: ['materials', 'physics', 'biomed'],
    keywords: ['chemistry', 'nano', 'catalysis', 'synthesis', 'characterization'],
    openAccess: true,
    format: 'access_oa',
  },
  {
    name: 'Nanoscale (example pattern)',
    publisherHint: 'Royal Society of Chemistry nanoscience pattern (verify OA options)',
    fields: ['materials', 'physics', 'devices'],
    keywords: ['nanoparticle', 'nanostructure', 'nanocomposite', 'nanowire', 'synthesis', 'nanocrystal'],
    format: 'full_article',
    caution: 'Example topical fit only — not an RSC endorsement.',
  },

  // —— Wiley (materials / devices / energy / ceramics) ——
  {
    name: 'Advanced Materials (example pattern)',
    publisherHint: 'Wiley high-impact materials pattern (verify scope/OA)',
    fields: ['materials', 'physics', 'devices', 'semiconductors'],
    keywords: [
      'advanced material',
      'nanostructure',
      'functional material',
      'energy storage',
      'optoelectronic',
      'catalyst',
      '2d material',
    ],
    format: 'full_article',
    caution: 'Highly selective — example topical fit only, not an acceptance signal.',
  },
  {
    name: 'Advanced Functional Materials (example pattern)',
    publisherHint: 'Wiley functional-materials pattern (verify scope/OA)',
    fields: ['materials', 'devices', 'physics'],
    keywords: [
      'functional material',
      'nanostructure',
      'energy conversion',
      'sensor',
      'catalyst',
      'composite',
      'coating',
    ],
    format: 'full_article',
    caution: 'Example topical fit only — not a Wiley endorsement.',
  },
  {
    name: 'Small (example pattern)',
    publisherHint: 'Wiley nano/micro-scale pattern (verify scope/OA)',
    fields: ['materials', 'devices', 'semiconductors', 'physics'],
    keywords: [
      'nano',
      'nanostructure',
      'nanoparticle',
      'nanodevice',
      'microfabrication',
      '2d material',
      'quantum dot',
    ],
    format: 'full_article',
    caution: 'Example topical fit only — confirm current scope yourself.',
  },
  {
    name: 'physica status solidi (RRL / a / b) (example pattern)',
    publisherHint: 'Wiley solid-state physics family pattern',
    fields: ['physics', 'semiconductors', 'materials'],
    keywords: [
      'solid state',
      'semiconductor',
      'bandgap',
      'epitaxy',
      'thin film',
      'doping',
      'heterostructure',
    ],
    format: 'letter',
    caution: 'Example pattern — RRL/a/b sub-series scope differs, verify yourself.',
  },
  {
    name: 'International Journal of Energy Research (example pattern)',
    publisherHint: 'Wiley energy-research pattern (verify scope/OA)',
    fields: ['materials', 'ee', 'general'],
    keywords: [
      'energy',
      'renewable',
      'battery',
      'fuel cell',
      'solar cell',
      'thermal management',
      'energy storage',
    ],
    format: 'full_article',
  },
  {
    name: 'Journal of the American Ceramic Society (example pattern)',
    publisherHint: 'Wiley (for the American Ceramic Society) pattern',
    fields: ['materials', 'physics'],
    keywords: ['ceramic', 'sintering', 'dielectric', 'oxide', 'microstructure', 'grain boundary'],
    format: 'full_article',
    caution: 'Example pattern only — confirm scope fits ceramics/inorganic materials.',
  },

  // —— Micro/nanotechnology, MEMS, and IOP/ACS gap-fill ——
  {
    name: 'Nanotechnology (IOP Publishing, example pattern)',
    publisherHint: 'IOP Publishing nanoscience pattern (verify scope/OA)',
    fields: ['materials', 'devices', 'semiconductors', 'physics'],
    keywords: [
      'nanowire',
      'nanotube',
      'nanoparticle',
      'quantum dot',
      'nanofabrication',
      '2d material',
      'nanostructure',
    ],
    format: 'full_article',
  },
  {
    name: 'Journal of Micromechanics and Microengineering (IOP Publishing, example pattern)',
    publisherHint: 'IOP MEMS / microfabrication pattern',
    fields: ['devices', 'sensors', 'semiconductors'],
    keywords: [
      'mems',
      'microfabrication',
      'microactuator',
      'microfluidic',
      'microstructure',
      'micromachining',
    ],
    format: 'full_article',
  },
  {
    name: 'Journal of Physics D: Applied Physics (IOP Publishing, example pattern)',
    publisherHint: 'IOP applied-physics pattern',
    fields: ['physics', 'materials', 'devices', 'semiconductors'],
    keywords: ['applied physics', 'thin film', 'plasma', 'dielectric', 'magnetic', 'plasmonic'],
    format: 'full_article',
  },
  {
    name: 'ACS Nano (example pattern)',
    publisherHint: 'American Chemical Society nanoscience pattern (verify OA options)',
    fields: ['materials', 'devices', 'physics', 'semiconductors'],
    keywords: [
      'nanoparticle',
      'nanomaterial',
      'nanostructure',
      '2d material',
      'catalysis',
      'nanomedicine',
      'nanocrystal',
    ],
    format: 'full_article',
    caution: 'Highly selective — example topical fit only, not an ACS endorsement.',
  },
  {
    name: 'Microsystems & Nanoengineering (Nature Portfolio, OA example)',
    publisherHint: 'Nature Portfolio open MEMS/NEMS example',
    fields: ['devices', 'sensors', 'semiconductors', 'materials'],
    keywords: [
      'mems',
      'nems',
      'microsystem',
      'microfabrication',
      'actuator',
      'lab-on-chip',
      'microfluidic',
    ],
    openAccess: true,
    format: 'access_oa',
    caution: 'Example OA title — not a Nature brand endorsement or acceptance claim.',
  },
  {
    name: 'IEEE Journal of Microelectromechanical Systems / JMEMS (example pattern)',
    publisherHint: 'IEEE MEMS society pattern',
    fields: ['devices', 'sensors', 'semiconductors'],
    keywords: [
      'mems',
      'microactuator',
      'microfabrication',
      'resonator',
      'accelerometer',
      'gyroscope',
      'microstructure',
    ],
    ieeeOriented: true,
    format: 'full_article',
  },

  // —— CS / ML / systems ——
  {
    name: 'Journal of Machine Learning Research (JMLR)',
    publisherHint: 'Open ML research journal (example)',
    fields: ['ml', 'cs'],
    keywords: [
      'machine learning',
      'statistical learning',
      'kernel',
      'bayesian',
      'optimization',
      'generalization',
    ],
    openAccess: true,
    format: 'full_article',
  },
  {
    name: 'Transactions on Machine Learning Research (TMLR)',
    publisherHint: 'Open ML transactions-style venue (example)',
    fields: ['ml', 'cs'],
    keywords: ['deep learning', 'representation', 'foundation model', 'llm', 'benchmark'],
    openAccess: true,
    format: 'full_article',
  },
  {
    name: 'ACM Transactions on … (example pattern)',
    publisherHint: 'ACM transactions-style venue (name pattern only)',
    fields: ['cs', 'systems', 'ml'],
    keywords: ['software', 'distributed', 'operating system', 'compiler', 'hci', 'database'],
    format: 'full_article',
    caution: 'Example pattern — confirm CFP and society scope yourself.',
  },
  {
    name: 'Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies (IMWUT) pattern',
    publisherHint: 'ACM UbiComp/IMWUT-style pattern',
    fields: ['systems', 'sensors', 'cs', 'ml'],
    keywords: ['wearable', 'ubiquitous', 'mobile sensing', 'activity recognition'],
    format: 'full_article',
  },
  {
    name: 'ACM Transactions on Sensor Networks (example pattern)',
    publisherHint: 'ACM TOSN pattern',
    fields: ['sensors', 'systems', 'communications', 'cs'],
    keywords: ['sensor network', 'wsn', 'routing', 'energy harvesting', 'coverage'],
    format: 'full_article',
  },
  {
    name: 'PeerJ Computer Science (OA example)',
    publisherHint: 'Open-access CS journal (example)',
    fields: ['cs', 'ml', 'systems'],
    keywords: ['software', 'algorithm', 'computer science', 'open science'],
    openAccess: true,
    format: 'access_oa',
  },

  // —— Biomed / multidisciplinary OA ——
  {
    name: 'PLOS ONE',
    publisherHint: 'Multidisciplinary open-access journal (example)',
    fields: ['biomed', 'general', 'physics', 'cs'],
    keywords: ['clinical', 'patient', 'biology', 'genome', 'trial', 'biomarker', 'epidemiolog'],
    openAccess: true,
    format: 'access_oa',
    caution: 'Broad scope OA; APC and editorial criteria still apply.',
  },
  {
    name: 'PLOS Computational Biology (example)',
    publisherHint: 'Open computational biology (example)',
    fields: ['biomed', 'cs', 'ml'],
    keywords: ['computational biology', 'systems biology', 'model organism', 'simulation'],
    openAccess: true,
    format: 'full_article',
  },
  {
    name: 'BMC Bioinformatics / related BMC series (example)',
    publisherHint: 'Open biomedical / computational biology family',
    fields: ['biomed', 'cs', 'ml'],
    keywords: ['bioinformatics', 'genomics', 'proteomics', 'sequence', 'pathway', 'omics'],
    openAccess: true,
    format: 'access_oa',
  },
  {
    name: 'BMC Medicine / BMC series (example family)',
    publisherHint: 'BMC open medical family (examples)',
    fields: ['biomed', 'general'],
    keywords: ['clinical', 'cohort', 'trial', 'diagnosis', 'therapy', 'public health'],
    openAccess: true,
    format: 'access_oa',
  },
  {
    name: 'Frontiers in … (example family)',
    publisherHint: 'Open-access publisher family',
    fields: ['biomed', 'general', 'ml', 'materials'],
    keywords: ['neuroscience', 'psychology', 'public health', 'ecology', 'materials science'],
    openAccess: true,
    format: 'access_oa',
    caution:
      'Some institutions scrutinize certain OA families — check local guidance before submitting.',
  },
  {
    name: 'Scientific Reports (Nature Portfolio OA example)',
    publisherHint: 'Nature Portfolio open multidisciplinary example',
    fields: ['general', 'physics', 'biomed', 'materials', 'cs'],
    keywords: ['multidisciplinary', 'experimental', 'characterization', 'validation'],
    openAccess: true,
    format: 'access_oa',
    caution: 'Example OA sister title — not a Nature brand endorsement or acceptance claim.',
  },
  {
    name: 'Nature Communications (OA sister example — verify scope)',
    publisherHint: 'Nature Portfolio OA communications example',
    fields: ['general', 'physics', 'biomed', 'materials', 'ml'],
    keywords: ['interdisciplinary', 'mechanism', 'discovery', 'high impact methods'],
    openAccess: true,
    format: 'full_article',
    caution: 'Highly selective; listed only as a topical example — never an acceptance prediction.',
  },
  {
    name: 'Communications Engineering / Biology / Physics (Nature Portfolio OA examples)',
    publisherHint: 'Nature Portfolio Communications* OA family examples',
    fields: ['ee', 'biomed', 'physics', 'materials', 'cs'],
    keywords: ['engineering', 'biology', 'physics', 'device', 'method'],
    openAccess: true,
    format: 'communication',
    caution: 'Sister OA titles — verify current aims & scope yourself.',
  },
  {
    name: 'Heliyon (Elsevier OA example)',
    publisherHint: 'Elsevier open multidisciplinary example',
    fields: ['general', 'biomed', 'ee', 'cs'],
    keywords: ['multidisciplinary', 'case study', 'applied'],
    openAccess: true,
    format: 'access_oa',
    caution: 'Example only — not Elsevier affiliation or quartile claim.',
  },
  {
    name: 'Results in … / Measurement journals (Elsevier short-result examples)',
    publisherHint: 'Elsevier short-results style examples',
    fields: ['ee', 'materials', 'sensors', 'general'],
    keywords: ['measurement', 'characterization', 'brief report', 'experimental result'],
    openAccess: true,
    format: 'communication',
    caution: 'Short-format examples — confirm journal series yourself.',
  },
  {
    name: 'SpringerOpen / BMC engineering titles (example family)',
    publisherHint: 'SpringerOpen engineering OA examples',
    fields: ['ee', 'cs', 'systems', 'materials'],
    keywords: ['engineering', 'applied science', 'prototype', 'validation'],
    openAccess: true,
    format: 'access_oa',
  },
  {
    name: 'EURASIP Journal on Advances in Signal Processing (OA example)',
    publisherHint: 'Open signal-processing journal example',
    fields: ['ee', 'communications', 'ml'],
    keywords: ['signal processing', 'filter', 'estimation', 'array processing'],
    openAccess: true,
    format: 'full_article',
  },

  // —— Preprint classes ——
  {
    name: 'arXiv cs.LG / cs.CV / cs.CL (preprint class)',
    publisherHint: 'arXiv subject class — preprint, not a journal',
    fields: ['ml', 'cs'],
    keywords: [
      'machine learning',
      'deep learning',
      'neural',
      'vision',
      'transformer',
      'diffusion',
      'llm',
      'nlp',
    ],
    openAccess: true,
    format: 'preprint',
    caution: 'Preprint server — not peer-reviewed acceptance or a quartile rank.',
  },
  {
    name: 'arXiv eess.SP / cs.IT / eess.SY (preprint class)',
    publisherHint: 'arXiv signal / information-theory / systems classes',
    fields: ['ee', 'communications', 'systems'],
    keywords: [
      'signal processing',
      'estimation',
      'filter',
      'information theory',
      'coding',
      'control',
    ],
    openAccess: true,
    format: 'preprint',
    caution: 'Preprint class only — not a journal decision.',
  },
  {
    name: 'arXiv cond-mat / physics.app-ph (preprint class)',
    publisherHint: 'arXiv condensed-matter / applied-physics classes',
    fields: ['physics', 'materials', 'semiconductors', 'devices'],
    keywords: ['condensed matter', 'thin film', 'superconductor', 'magnetism', 'semiconductor'],
    openAccess: true,
    format: 'preprint',
  },
  {
    name: 'arXiv cs.NI / cs.DC / cs.SE (preprint class)',
    publisherHint: 'arXiv networking / distributed / software classes',
    fields: ['cs', 'systems', 'communications'],
    keywords: ['network', 'distributed', 'cloud', 'software engineering', 'protocol'],
    openAccess: true,
    format: 'preprint',
  },
  {
    name: 'bioRxiv / medRxiv (preprint servers)',
    publisherHint: 'Life / clinical science preprint servers',
    fields: ['biomed'],
    keywords: ['clinical', 'biology', 'genome', 'trial', 'biomarker', 'cell'],
    openAccess: true,
    format: 'preprint',
    caution: 'Preprints are not journal acceptance; medRxiv has screening rules.',
  },
  {
    name: 'TechRxiv (IEEE-related preprint example)',
    publisherHint: 'Engineering preprint server example',
    fields: ['ee', 'cs', 'systems', 'communications', 'semiconductors'],
    keywords: ['engineering', 'ieee', 'prototype', 'hardware'],
    openAccess: true,
    format: 'preprint',
    ieeeOriented: true,
  },
];

/** Keyword → field hints used when scoring topical fit from title/abstract. */
export const FIELD_LEXICON: { field: VenueField; terms: string[] }[] = [
  {
    field: 'ml',
    terms: [
      'machine learning',
      'deep learning',
      'neural',
      'transformer',
      'cnn',
      'llm',
      'reinforcement learning',
      'classification',
      'supervised',
      'unsupervised',
      'foundation model',
    ],
  },
  {
    field: 'cs',
    terms: [
      'algorithm',
      'software',
      'compiler',
      'distributed',
      'database',
      'graph',
      'complexity',
      'operating system',
      'cloud',
      'cybersecurity',
    ],
  },
  {
    field: 'ee',
    terms: [
      'voltage',
      'circuit',
      'analog',
      'power electronics',
      'fpga',
      'vlsi',
      'converter',
      'amplifier',
      'rf',
      'microwave',
    ],
  },
  {
    field: 'semiconductors',
    terms: [
      'semiconductor',
      'cmos',
      'mosfet',
      'finfet',
      'gan',
      'sic',
      'wafer',
      'lithography',
      'bandgap',
      'epitaxy',
      'doped',
      'heterojunction',
    ],
  },
  {
    field: 'sensors',
    terms: [
      'sensor',
      'sensing',
      'transducer',
      'mems',
      'biosensor',
      'accelerometer',
      'gas sensor',
      'calibration',
      'wearable',
    ],
  },
  {
    field: 'materials',
    terms: [
      'material',
      'thin film',
      'polymer',
      'alloy',
      'perovskite',
      'graphene',
      '2d material',
      'nanomaterial',
      'composite',
      'dielectric',
      'nanostructure',
      'nanoparticle',
      'nanowire',
      'nanotube',
      'nanocomposite',
      'ceramic',
      'sintering',
      'quantum dot',
    ],
  },
  {
    field: 'devices',
    terms: [
      'device',
      'transistor',
      'diode',
      'mems',
      'nems',
      'actuator',
      'photodetector',
      'led',
      'solar cell',
      'battery',
      'electrode',
      'microfabrication',
      'microactuator',
      'microfluidic',
      'micromachining',
      'lab-on-chip',
      'resonator',
      'gyroscope',
    ],
  },
  {
    field: 'communications',
    terms: [
      'wireless',
      'mimo',
      'ofdm',
      '5g',
      '6g',
      'beamforming',
      'spectrum',
      'modulation',
      'antenna',
      'propagation',
    ],
  },
  {
    field: 'systems',
    terms: [
      'embedded',
      'iot',
      'cyber-physical',
      'control system',
      'robot',
      'sensor network',
      'edge computing',
      'automation',
    ],
  },
  {
    field: 'biomed',
    terms: [
      'clinical',
      'patient',
      'medical',
      'genomic',
      'bioinformat',
      'diagnosis',
      'therapy',
      'mri',
      'eeg',
      'ecg',
      'biomarker',
    ],
  },
  {
    field: 'physics',
    terms: [
      'quantum',
      'photon',
      'lattice',
      'condensed matter',
      'particle',
      'optics',
      'plasmon',
      'superconduct',
    ],
  },
];
