/**
 * Render CSL-JSON bibliography entries via citation-js + plugin-csl.
 */

import { Cite } from '@citation-js/core';
import '@citation-js/plugin-csl';
import { getStyle, type ReformatStyle } from './styles';
import type { ParsedCslRef } from './parseToCsl';

export interface RenderedRef {
  index: number;
  raw: string;
  rendered: string;
  confidence: ParsedCslRef['confidence'];
  source: ParsedCslRef['source'];
  note?: string;
  csl: ParsedCslRef['csl'];
}

function fallbackRender(entry: ParsedCslRef): string {
  const authors =
    entry.csl.author
      ?.map((a) => a.literal || [a.family, a.given].filter(Boolean).join(', '))
      .filter(Boolean)
      .join('; ') || '';
  const year = entry.csl.issued?.['date-parts']?.[0]?.[0];
  const title = entry.csl.title || 'Untitled';
  const venue = entry.csl['container-title'] || '';
  const doi = entry.csl.DOI ? ` doi:${entry.csl.DOI}` : '';
  return [authors, year ? `(${year})` : '', title, venue].filter(Boolean).join('. ') + doi;
}

export function renderOne(entry: ParsedCslRef, style: ReformatStyle | string): string {
  const s = typeof style === 'string' ? getStyle(style) : style;
  if (s.unsupported) {
    return fallbackRender(entry) + ' [footnote style unsupported in MVP]';
  }
  try {
    const cite = new Cite(entry.csl);
    const out = cite
      .format('bibliography', {
        format: 'text',
        template: s.template,
        lang: 'en-US',
      })
      .trim();
    return out || fallbackRender(entry);
  } catch {
    return fallbackRender(entry);
  }
}

export function renderBibliography(
  entries: ParsedCslRef[],
  styleId: string
): RenderedRef[] {
  const style = getStyle(styleId);
  return entries.map((e) => ({
    index: e.index,
    raw: e.raw,
    rendered: renderOne(e, style),
    confidence: e.confidence,
    source: e.source,
    note: e.note || style.note,
    csl: e.csl,
  }));
}

/** Plain-text bibliography for export (numbered). */
export function formatBibliographyText(rendered: RenderedRef[], styleId: string): string {
  const style = getStyle(styleId);
  const lines = [
    `# Restyled bibliography (${style.label})`,
    '',
    'Generated by Revision Assistant Resubmission Reformatter.',
    'Verify every entry against the target journal author guidelines before submission.',
    style.note ? `Note: ${style.note}` : '',
    '',
  ].filter((l) => l !== undefined);

  for (const r of rendered) {
    lines.push(`[${r.index}] ${r.rendered}`);
    lines.push('');
  }
  return lines.join('\n');
}
